---
- name: Install vdirsyncer into virtual environment
  pip: name=vdirsyncer
       virtualenv=/usr/local/env/pim
       virtualenv_command=virtualenv3

- name: Install khard into virtual environment
  pip: name=khard
       virtualenv=/usr/local/env/pim
       virtualenv_command=virtualenv3

- name: Install khal into virtual environment
  pip: name=khal
       virtualenv=/usr/local/env/pim
       virtualenv_command=virtualenv3

- name: Link vdirsyncer to bin
  file: src=/usr/local/env/pim/bin/vdirsyncer
        dest=/usr/local/bin/vdirsyncer
        state=link

- name: Link khard to bin
  file: src=/usr/local/env/pim/bin/khard
        dest=/usr/local/bin/khard
        state=link

- name: Link khal to bin
  file: src=/usr/local/env/pim/bin/khal
        dest=/usr/local/bin/khal
        state=link
